version: '3.8'

services:
  ###############################################################
  # mysql-engine: https://hub.docker.com/_/mysql
  ###############################################################
  db:
    image: localhost:5000/mysql:latest
    container_name: my-sql
    hostname: my-sql
    restart: always
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
#      MYSQL_DATABASE: my-schema-name
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: P@ssw0rd
    mem_limit: 500m
    mem_reservation: 100m
    privileged: true
    volumes:
      - /mysql-data/:/var/lib/mysql

  ###############################################################
  # mysql-engine: https://hub.docker.com/r/phpmyadmin/phpmyadmin/
  ###############################################################
  phpmyadmin:
    image: localhost:5000/phpmyadmin:latest
    container_name: php-myadmin
    hostname: php-myadmin
    restart: always
    restart: always
    ports:
      - 4040:80
    environment:
#?      - PMA_ARBITRARY=1
    PMA_HOST: remote-mysql-ip
    depends_on:
    - my-sql
    links:
    - my-sql:my-sql
    mem_limit: 250m
    mem_reservation: 50m