version: '3.7'
services:
  passbolt:
    image: localhost:5000/passbolt:latest
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    tty: true
    environment:
      APP_FULL_BASE_URL: https://192.168.1.34/
      DATASOURCES_DEFAULT_HOST: "192.168.1.34"
      DATASOURCES_DEFAULT_USERNAME: "admin"
      DATASOURCES_DEFAULT_PASSWORD: "*****"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
      PASSBOLT_SSL_FORCE: "true"
      EMAIL_TRANSPORT_DEFAULT_HOST: "smtp.gmail.com"
      EMAIL_TRANSPORT_DEFAULT_PORT: "587"
      EMAIL_TRANSPORT_DEFAULT_USERNAME: "parhizkari.afshin@gmail.com"
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: "*****"
      EMAIL_DEFAULT_FROM: "parhizkari.afshin@gmail.com"
      EMAIL_TRANSPORT_DEFAULT_TLS: "true"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command: ["/usr/bin/wait-for.sh", "-t", "0", "192.168.1.34:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433

volumes:
  gpg_volume:
  jwt_volume: